version: "3.8"
services:
  server:
    image: nginx:stable-alpine
    ports:
      - '8000:80'
    volumes:
        # Custom config to nginx path
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  php:
    build: 
      context: ./docker
      dockerfile: Dockerfile.php
    volumes: 
        # Delegated means changes must be sync after sometime to container
      - ./src:/var/www/html:delegated
  mysql:
    image: mysql:5.7
    env_file: ./env/mysql.env
  composer:
    build: 
      context: ./docker
      dockerfile: Dockerfile.composer
    volumes: 
      - ./src:/var/www/html
  # artisan:
  # npm:
