version: "3.8"
services:
  server:
    image: nginx:stable-alpine
    ports:
      - '8000:80'
    volumes:
        # Custom config to nginx path
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        # All the php code must be accessible to nginx server
      - ./src:/var/www/html
    depends_on: 
      - php
      - mysql
  php:
    build: 
      context: ./docker
      dockerfile: Dockerfile.php
    volumes: 
        # Delegated means changes must be sync after sometime to container
      - ./src:/var/www/html:delegated
  mysql:
    image: mysql:5.7
    env_file: ./env/mysql.env
  composer:
    build: 
      context: ./docker
      dockerfile: Dockerfile.composer
    volumes: 
      - ./src:/var/www/html
  artisan:
    build: 
      context: ./docker
      dockerfile: Dockerfile.php
    volumes: 
      - ./src:/var/www/html
    # Overriding dockerfle by adding an entryfile
    # We can create a separate dockerfile for artisan instead of this
    entrypoint: ["php", "/var/www/html/artisan"]
  npm:
    image: node:14-alpine
    # Below 2 commands are substitue to creating our own utility docker image
    # Utility command `docker-compose run --rm -v ${pwd}:/var/www/html npm init`
    working_dir: /var/www/html
    entrypoint: ["npm"]

