FROM composer:latest
WORKDIR /var/www/html
# Ignores platform related dependecny issues
ENTRYPOINT [ "composer", "--ignore-platform-reqs" ]

# ----------------------------
# Use below dockerfile to fix permission related issues
# ----------------------------
# FROM composer:latest
# RUN addgroup -g 1000 laravel && adduser -G laravel -g laravel -s /bin/sh -D laravel
# USER laravel
# WORKDIR /var/www/html
# ENTRYPOINT [ "composer", "--ignore-platform-reqs" ]
